// <auto-generated />
using CreditCardShopping.ProductAPI.Model.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CreditCardShopping.ProductAPI.Migrations
{
    [DbContext(typeof(MySQLContext))]
    [Migration("20220615122546_AddMigrationNotebook")]
    partial class AddMigrationNotebook
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("CreditCardShopping.ProductAPI.Model.Product", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("category_name");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("description");

                    b.Property<string>("ImageURL")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)")
                        .HasColumnName("image_url");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("name");

                    b.Property<double>("Price")
                        .HasColumnType("double")
                        .HasColumnName("price");

                    b.HasKey("Id");

                    b.ToTable("product");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CategoryName = "Notebook Gamer",
                            Description = "GTX 1650, intel core i5, 8GB de RAM, 512GB SSD",
                            ImageURL = "https://www.kabum.com.br/conteudo/descricao/113442/img/header-image.png",
                            Name = "Notebook Acer Nitro 5",
                            Price = 5199.9899999999998
                        },
                        new
                        {
                            Id = 2L,
                            CategoryName = "Placas de Vídeo",
                            Description = "Com a GeForce RTX™ 3060 Ti e a RTX™ 3060, você pode jogar os games mais atuais usando o poder da Ampere, a 2ª geração da arquitetura RTX da NVIDIA. Obtenha um desempenho incrível com Ray Tracing Cores e Tensor Cores aprimorados, novos multiprocessadores de streaming e memória G6 de alta velocidade.",
                            ImageURL = "https://images.nvidia.com/aem-dam/Solutions/geforce/ampere/rtx-3060-ti/geforce-rtx-3060-ti-product-gallery-full-screen-3840-3-bl.jpg",
                            Name = "GeForce RTX 3060",
                            Price = 6999.8999999999996
                        },
                        new
                        {
                            Id = 3L,
                            CategoryName = "Mouse Gamer",
                            Description = "Tecnologia LIGHTSPEED, RGB LIGHTSYNC, Design Ambidestro, 6 Botões Programáveis, Sensor HERO 25K e Bateria Recarregável - Compatível com POWERPLAY",
                            ImageURL = "https://www.logitechstore.com.br/media/catalog/product/cache/1/image/634x545/9df78eab33525d08d6e5fb8d27136e95/p/r/pro-wireless.png",
                            Name = "Mouse Gamer Sem Fio Logitech G PRO Wireless",
                            Price = 799.89999999999998
                        },
                        new
                        {
                            Id = 4L,
                            CategoryName = "Headset Gamer",
                            Description = "O HyperX Cloud foi criado para ser um headset gamer ultraconfortável com um som espetacular. Pensamos muito nos detalhes, como nossa espuma memory foam exclusiva HyperX, o couro sintético premium, a força de aperto do arco da cabeça reduzida e o peso equilibrado para criar um headset que fosse confortável para longas sessões de jogo.",
                            ImageURL = "https://prosettings.net/wp-content/uploads/2020/11/HyperX-Cloud-II-Wireless-Transparent-Background.png",
                            Name = "Headset Sem Fio Gamer HyperX Cloud II",
                            Price = 1199.9000000000001
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
